### ISSUE TITLE
Move gh-pages site to LouisvilleDataCommons.org URL

### ISSUE THREAD

**Issue by parkerduff** [LouisvilleDataCommons/LouisvilleDataCommons.github.io#6]
Docusaurus update: https://docusaurus.io/docs/deployment#deploying-to-github-pages
* Update docusaurus configuration file
* Update repository name
* Add file to static folder

Domain
* Configure from domain provider

Linktree
* Delete subscription

**Comment by parkerduff** [comment]
@ajdrake I made a new branch with the docusaurus changes. I'll let you finish it up with the domain stuff

**Comment by ajdrake** [comment]
@parkerduff is there a place I can see the site on gh pages?

**Comment by parkerduff** [comment]
https://louisvilledatacommons.github.io

**Comment by eozgener** [comment]
Here is documentation from GitHub on using a custom domain: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by ajdrake** [comment]
![Screen Shot 2022-01-22 at 5 50 26 PM](https://user-images.githubusercontent.com/1540701/150657885-d81c7901-7a4d-4faa-9d1a-a8c5cc7ec955.png)
![Screen Shot 2022-01-22 at 5 50 51 PM](https://user-images.githubusercontent.com/1540701/150657887-f0a24880-c9c4-4554-b7a7-abf2746a12fc.png)

@eozgener @parkerduff I'm having some issues getting it to enforce https, but otherwise the domain is moved over. Any ideas on why I'm not able to enforce https?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#https-errors

**Comment by parkerduff** [comment]
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

"Optionally, to enforce HTTPS encryption for your site, select Enforce HTTPS. It can take up to 24 hours before this option is available. For more information, see "Securing your GitHub Pages site with HTTPS.""

I would check it again tomorrow afternoon, and if that option is still not available, maybe check out this section: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by ajdrake** [comment]
playing with these settings seemed to "fix" it today

https://community.cloudflare.com/t/github-pages-require-disabling-cfs-http-proxy/147401
![Screen Shot 2022-01-23 at 8 21 47 AM](https://user-images.githubusercontent.com/1540701/150680558-f6c22517-1a0e-426c-91c0-9a53b60f0345.png)
![Screen Shot 2022-01-23 at 8 22 03 AM](https://user-images.githubusercontent.com/1540701/150680560-aff2f222-0599-4b1d-8889-b123e9bfc589.png)
